// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: ics_file_manager/ics_file_manager.proto

package icsfilemanager

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// CreateICSFile adds new *.ics file record
	CreateICSFile(ctx context.Context, in *CreateICSFileRequest, opts ...grpc.CallOption) (*ICSFile, error)
	// DeleteICSFile deletes *.ics file record
	DeleteICSFile(ctx context.Context, in *DeleteICSFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetICSFile returns *.ics file record
	GetICSFile(ctx context.Context, in *GetICSFileRequest, opts ...grpc.CallOption) (*ICSFile, error)
	// GetICSFileByGameID returns *.ics file record by game ID
	GetICSFileByGameID(ctx context.Context, in *GetICSFileByGameIDRequest, opts ...grpc.CallOption) (*ICSFile, error)
	// ListICSFiles returns all *.ics file records
	ListICSFiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListICSFilesResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) CreateICSFile(ctx context.Context, in *CreateICSFileRequest, opts ...grpc.CallOption) (*ICSFile, error) {
	out := new(ICSFile)
	err := c.cc.Invoke(ctx, "/ics_file_manager.Service/CreateICSFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) DeleteICSFile(ctx context.Context, in *DeleteICSFileRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ics_file_manager.Service/DeleteICSFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetICSFile(ctx context.Context, in *GetICSFileRequest, opts ...grpc.CallOption) (*ICSFile, error) {
	out := new(ICSFile)
	err := c.cc.Invoke(ctx, "/ics_file_manager.Service/GetICSFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetICSFileByGameID(ctx context.Context, in *GetICSFileByGameIDRequest, opts ...grpc.CallOption) (*ICSFile, error) {
	out := new(ICSFile)
	err := c.cc.Invoke(ctx, "/ics_file_manager.Service/GetICSFileByGameID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ListICSFiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListICSFilesResponse, error) {
	out := new(ListICSFilesResponse)
	err := c.cc.Invoke(ctx, "/ics_file_manager.Service/ListICSFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	// CreateICSFile adds new *.ics file record
	CreateICSFile(context.Context, *CreateICSFileRequest) (*ICSFile, error)
	// DeleteICSFile deletes *.ics file record
	DeleteICSFile(context.Context, *DeleteICSFileRequest) (*emptypb.Empty, error)
	// GetICSFile returns *.ics file record
	GetICSFile(context.Context, *GetICSFileRequest) (*ICSFile, error)
	// GetICSFileByGameID returns *.ics file record by game ID
	GetICSFileByGameID(context.Context, *GetICSFileByGameIDRequest) (*ICSFile, error)
	// ListICSFiles returns all *.ics file records
	ListICSFiles(context.Context, *emptypb.Empty) (*ListICSFilesResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) CreateICSFile(context.Context, *CreateICSFileRequest) (*ICSFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateICSFile not implemented")
}
func (UnimplementedServiceServer) DeleteICSFile(context.Context, *DeleteICSFileRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteICSFile not implemented")
}
func (UnimplementedServiceServer) GetICSFile(context.Context, *GetICSFileRequest) (*ICSFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetICSFile not implemented")
}
func (UnimplementedServiceServer) GetICSFileByGameID(context.Context, *GetICSFileByGameIDRequest) (*ICSFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetICSFileByGameID not implemented")
}
func (UnimplementedServiceServer) ListICSFiles(context.Context, *emptypb.Empty) (*ListICSFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListICSFiles not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_CreateICSFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateICSFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateICSFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ics_file_manager.Service/CreateICSFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateICSFile(ctx, req.(*CreateICSFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_DeleteICSFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteICSFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DeleteICSFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ics_file_manager.Service/DeleteICSFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DeleteICSFile(ctx, req.(*DeleteICSFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetICSFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetICSFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetICSFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ics_file_manager.Service/GetICSFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetICSFile(ctx, req.(*GetICSFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetICSFileByGameID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetICSFileByGameIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetICSFileByGameID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ics_file_manager.Service/GetICSFileByGameID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetICSFileByGameID(ctx, req.(*GetICSFileByGameIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ListICSFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ListICSFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ics_file_manager.Service/ListICSFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ListICSFiles(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ics_file_manager.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateICSFile",
			Handler:    _Service_CreateICSFile_Handler,
		},
		{
			MethodName: "DeleteICSFile",
			Handler:    _Service_DeleteICSFile_Handler,
		},
		{
			MethodName: "GetICSFile",
			Handler:    _Service_GetICSFile_Handler,
		},
		{
			MethodName: "GetICSFileByGameID",
			Handler:    _Service_GetICSFileByGameID_Handler,
		},
		{
			MethodName: "ListICSFiles",
			Handler:    _Service_ListICSFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ics_file_manager/ics_file_manager.proto",
}
