// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	game "github.com/nikita5637/quiz-registrator-api/pkg/pb/game"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// GameServiceClient is an autogenerated mock type for the GameServiceClient type
type GameServiceClient struct {
	mock.Mock
}

type GameServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GameServiceClient) EXPECT() *GameServiceClient_Expecter {
	return &GameServiceClient_Expecter{mock: &_m.Mock}
}

// GetGame provides a mock function with given fields: ctx, in, opts
func (_m *GameServiceClient) GetGame(ctx context.Context, in *game.GetGameRequest, opts ...grpc.CallOption) (*game.Game, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *game.Game
	if rf, ok := ret.Get(0).(func(context.Context, *game.GetGameRequest, ...grpc.CallOption) *game.Game); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*game.Game)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *game.GetGameRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameServiceClient_GetGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGame'
type GameServiceClient_GetGame_Call struct {
	*mock.Call
}

// GetGame is a helper method to define mock.On call
//  - ctx context.Context
//  - in *game.GetGameRequest
//  - opts ...grpc.CallOption
func (_e *GameServiceClient_Expecter) GetGame(ctx interface{}, in interface{}, opts ...interface{}) *GameServiceClient_GetGame_Call {
	return &GameServiceClient_GetGame_Call{Call: _e.mock.On("GetGame",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *GameServiceClient_GetGame_Call) Run(run func(ctx context.Context, in *game.GetGameRequest, opts ...grpc.CallOption)) *GameServiceClient_GetGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*game.GetGameRequest), variadicArgs...)
	})
	return _c
}

func (_c *GameServiceClient_GetGame_Call) Return(_a0 *game.Game, _a1 error) *GameServiceClient_GetGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewGameServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewGameServiceClient creates a new instance of GameServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGameServiceClient(t mockConstructorTestingTNewGameServiceClient) *GameServiceClient {
	mock := &GameServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
