// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	registrator "github.com/nikita5637/quiz-registrator-api/pkg/pb/registrator"
)

// RegistratorServiceClient is an autogenerated mock type for the RegistratorServiceClient type
type RegistratorServiceClient struct {
	mock.Mock
}

type RegistratorServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RegistratorServiceClient) EXPECT() *RegistratorServiceClient_Expecter {
	return &RegistratorServiceClient_Expecter{mock: &_m.Mock}
}

// GetGameByID provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetGameByID(ctx context.Context, in *registrator.GetGameByIDRequest, opts ...grpc.CallOption) (*registrator.GetGameByIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetGameByIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetGameByIDRequest, ...grpc.CallOption) *registrator.GetGameByIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetGameByIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetGameByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetGameByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGameByID'
type RegistratorServiceClient_GetGameByID_Call struct {
	*mock.Call
}

// GetGameByID is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetGameByIDRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetGameByID(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetGameByID_Call {
	return &RegistratorServiceClient_GetGameByID_Call{Call: _e.mock.On("GetGameByID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetGameByID_Call) Run(run func(ctx context.Context, in *registrator.GetGameByIDRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetGameByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetGameByIDRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetGameByID_Call) Return(_a0 *registrator.GetGameByIDResponse, _a1 error) *RegistratorServiceClient_GetGameByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewRegistratorServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegistratorServiceClient creates a new instance of RegistratorServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegistratorServiceClient(t mockConstructorTestingTNewRegistratorServiceClient) *RegistratorServiceClient {
	mock := &RegistratorServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
