// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	registrator "github.com/nikita5637/quiz-registrator-api/pkg/pb/registrator"
)

// RegistratorServiceClient is an autogenerated mock type for the RegistratorServiceClient type
type RegistratorServiceClient struct {
	mock.Mock
}

type RegistratorServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RegistratorServiceClient) EXPECT() *RegistratorServiceClient_Expecter {
	return &RegistratorServiceClient_Expecter{mock: &_m.Mock}
}

// AddGame provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) AddGame(ctx context.Context, in *registrator.AddGameRequest, opts ...grpc.CallOption) (*registrator.AddGameResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.AddGameResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.AddGameRequest, ...grpc.CallOption) *registrator.AddGameResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.AddGameResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.AddGameRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_AddGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGame'
type RegistratorServiceClient_AddGame_Call struct {
	*mock.Call
}

// AddGame is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.AddGameRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) AddGame(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_AddGame_Call {
	return &RegistratorServiceClient_AddGame_Call{Call: _e.mock.On("AddGame",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_AddGame_Call) Run(run func(ctx context.Context, in *registrator.AddGameRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_AddGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.AddGameRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_AddGame_Call) Return(_a0 *registrator.AddGameResponse, _a1 error) *RegistratorServiceClient_AddGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// AddGames provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) AddGames(ctx context.Context, in *registrator.AddGamesRequest, opts ...grpc.CallOption) (*registrator.AddGamesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.AddGamesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.AddGamesRequest, ...grpc.CallOption) *registrator.AddGamesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.AddGamesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.AddGamesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_AddGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGames'
type RegistratorServiceClient_AddGames_Call struct {
	*mock.Call
}

// AddGames is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.AddGamesRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) AddGames(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_AddGames_Call {
	return &RegistratorServiceClient_AddGames_Call{Call: _e.mock.On("AddGames",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_AddGames_Call) Run(run func(ctx context.Context, in *registrator.AddGamesRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_AddGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.AddGamesRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_AddGames_Call) Return(_a0 *registrator.AddGamesResponse, _a1 error) *RegistratorServiceClient_AddGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) CreateUser(ctx context.Context, in *registrator.CreateUserRequest, opts ...grpc.CallOption) (*registrator.CreateUserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.CreateUserResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.CreateUserRequest, ...grpc.CallOption) *registrator.CreateUserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.CreateUserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.CreateUserRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type RegistratorServiceClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.CreateUserRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) CreateUser(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_CreateUser_Call {
	return &RegistratorServiceClient_CreateUser_Call{Call: _e.mock.On("CreateUser",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_CreateUser_Call) Run(run func(ctx context.Context, in *registrator.CreateUserRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.CreateUserRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_CreateUser_Call) Return(_a0 *registrator.CreateUserResponse, _a1 error) *RegistratorServiceClient_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DeleteGame provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) DeleteGame(ctx context.Context, in *registrator.DeleteGameRequest, opts ...grpc.CallOption) (*registrator.DeleteGameResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.DeleteGameResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.DeleteGameRequest, ...grpc.CallOption) *registrator.DeleteGameResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.DeleteGameResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.DeleteGameRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_DeleteGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGame'
type RegistratorServiceClient_DeleteGame_Call struct {
	*mock.Call
}

// DeleteGame is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.DeleteGameRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) DeleteGame(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_DeleteGame_Call {
	return &RegistratorServiceClient_DeleteGame_Call{Call: _e.mock.On("DeleteGame",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_DeleteGame_Call) Run(run func(ctx context.Context, in *registrator.DeleteGameRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_DeleteGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.DeleteGameRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_DeleteGame_Call) Return(_a0 *registrator.DeleteGameResponse, _a1 error) *RegistratorServiceClient_DeleteGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetGameByID provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetGameByID(ctx context.Context, in *registrator.GetGameByIDRequest, opts ...grpc.CallOption) (*registrator.GetGameByIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetGameByIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetGameByIDRequest, ...grpc.CallOption) *registrator.GetGameByIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetGameByIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetGameByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetGameByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGameByID'
type RegistratorServiceClient_GetGameByID_Call struct {
	*mock.Call
}

// GetGameByID is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetGameByIDRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetGameByID(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetGameByID_Call {
	return &RegistratorServiceClient_GetGameByID_Call{Call: _e.mock.On("GetGameByID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetGameByID_Call) Run(run func(ctx context.Context, in *registrator.GetGameByIDRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetGameByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetGameByIDRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetGameByID_Call) Return(_a0 *registrator.GetGameByIDResponse, _a1 error) *RegistratorServiceClient_GetGameByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetGames provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetGames(ctx context.Context, in *registrator.GetGamesRequest, opts ...grpc.CallOption) (*registrator.GetGamesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetGamesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetGamesRequest, ...grpc.CallOption) *registrator.GetGamesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetGamesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetGamesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGames'
type RegistratorServiceClient_GetGames_Call struct {
	*mock.Call
}

// GetGames is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetGamesRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetGames(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetGames_Call {
	return &RegistratorServiceClient_GetGames_Call{Call: _e.mock.On("GetGames",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetGames_Call) Run(run func(ctx context.Context, in *registrator.GetGamesRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetGamesRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetGames_Call) Return(_a0 *registrator.GetGamesResponse, _a1 error) *RegistratorServiceClient_GetGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetLeagueByID provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetLeagueByID(ctx context.Context, in *registrator.GetLeagueByIDRequest, opts ...grpc.CallOption) (*registrator.GetLeagueByIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetLeagueByIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetLeagueByIDRequest, ...grpc.CallOption) *registrator.GetLeagueByIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetLeagueByIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetLeagueByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetLeagueByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeagueByID'
type RegistratorServiceClient_GetLeagueByID_Call struct {
	*mock.Call
}

// GetLeagueByID is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetLeagueByIDRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetLeagueByID(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetLeagueByID_Call {
	return &RegistratorServiceClient_GetLeagueByID_Call{Call: _e.mock.On("GetLeagueByID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetLeagueByID_Call) Run(run func(ctx context.Context, in *registrator.GetLeagueByIDRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetLeagueByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetLeagueByIDRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetLeagueByID_Call) Return(_a0 *registrator.GetLeagueByIDResponse, _a1 error) *RegistratorServiceClient_GetLeagueByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetPlaceByID provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetPlaceByID(ctx context.Context, in *registrator.GetPlaceByIDRequest, opts ...grpc.CallOption) (*registrator.GetPlaceByIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetPlaceByIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetPlaceByIDRequest, ...grpc.CallOption) *registrator.GetPlaceByIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetPlaceByIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetPlaceByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetPlaceByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlaceByID'
type RegistratorServiceClient_GetPlaceByID_Call struct {
	*mock.Call
}

// GetPlaceByID is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetPlaceByIDRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetPlaceByID(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetPlaceByID_Call {
	return &RegistratorServiceClient_GetPlaceByID_Call{Call: _e.mock.On("GetPlaceByID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetPlaceByID_Call) Run(run func(ctx context.Context, in *registrator.GetPlaceByIDRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetPlaceByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetPlaceByIDRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetPlaceByID_Call) Return(_a0 *registrator.GetPlaceByIDResponse, _a1 error) *RegistratorServiceClient_GetPlaceByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetPlaceByNameAndAddress provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetPlaceByNameAndAddress(ctx context.Context, in *registrator.GetPlaceByNameAndAddressRequest, opts ...grpc.CallOption) (*registrator.GetPlaceByNameAndAddressResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetPlaceByNameAndAddressResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetPlaceByNameAndAddressRequest, ...grpc.CallOption) *registrator.GetPlaceByNameAndAddressResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetPlaceByNameAndAddressResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetPlaceByNameAndAddressRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetPlaceByNameAndAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlaceByNameAndAddress'
type RegistratorServiceClient_GetPlaceByNameAndAddress_Call struct {
	*mock.Call
}

// GetPlaceByNameAndAddress is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetPlaceByNameAndAddressRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetPlaceByNameAndAddress(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetPlaceByNameAndAddress_Call {
	return &RegistratorServiceClient_GetPlaceByNameAndAddress_Call{Call: _e.mock.On("GetPlaceByNameAndAddress",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetPlaceByNameAndAddress_Call) Run(run func(ctx context.Context, in *registrator.GetPlaceByNameAndAddressRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetPlaceByNameAndAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetPlaceByNameAndAddressRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetPlaceByNameAndAddress_Call) Return(_a0 *registrator.GetPlaceByNameAndAddressResponse, _a1 error) *RegistratorServiceClient_GetPlaceByNameAndAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetPlayersByGameID provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetPlayersByGameID(ctx context.Context, in *registrator.GetPlayersByGameIDRequest, opts ...grpc.CallOption) (*registrator.GetPlayersByGameIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetPlayersByGameIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetPlayersByGameIDRequest, ...grpc.CallOption) *registrator.GetPlayersByGameIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetPlayersByGameIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetPlayersByGameIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetPlayersByGameID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayersByGameID'
type RegistratorServiceClient_GetPlayersByGameID_Call struct {
	*mock.Call
}

// GetPlayersByGameID is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetPlayersByGameIDRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetPlayersByGameID(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetPlayersByGameID_Call {
	return &RegistratorServiceClient_GetPlayersByGameID_Call{Call: _e.mock.On("GetPlayersByGameID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetPlayersByGameID_Call) Run(run func(ctx context.Context, in *registrator.GetPlayersByGameIDRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetPlayersByGameID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetPlayersByGameIDRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetPlayersByGameID_Call) Return(_a0 *registrator.GetPlayersByGameIDResponse, _a1 error) *RegistratorServiceClient_GetPlayersByGameID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetRegisteredGames provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetRegisteredGames(ctx context.Context, in *registrator.GetRegisteredGamesRequest, opts ...grpc.CallOption) (*registrator.GetRegisteredGamesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetRegisteredGamesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetRegisteredGamesRequest, ...grpc.CallOption) *registrator.GetRegisteredGamesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetRegisteredGamesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetRegisteredGamesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetRegisteredGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegisteredGames'
type RegistratorServiceClient_GetRegisteredGames_Call struct {
	*mock.Call
}

// GetRegisteredGames is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetRegisteredGamesRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetRegisteredGames(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetRegisteredGames_Call {
	return &RegistratorServiceClient_GetRegisteredGames_Call{Call: _e.mock.On("GetRegisteredGames",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetRegisteredGames_Call) Run(run func(ctx context.Context, in *registrator.GetRegisteredGamesRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetRegisteredGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetRegisteredGamesRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetRegisteredGames_Call) Return(_a0 *registrator.GetRegisteredGamesResponse, _a1 error) *RegistratorServiceClient_GetRegisteredGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetUser provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetUser(ctx context.Context, in *registrator.GetUserRequest, opts ...grpc.CallOption) (*registrator.GetUserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetUserResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetUserRequest, ...grpc.CallOption) *registrator.GetUserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetUserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetUserRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type RegistratorServiceClient_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetUserRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetUser(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetUser_Call {
	return &RegistratorServiceClient_GetUser_Call{Call: _e.mock.On("GetUser",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetUser_Call) Run(run func(ctx context.Context, in *registrator.GetUserRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetUserRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetUser_Call) Return(_a0 *registrator.GetUserResponse, _a1 error) *RegistratorServiceClient_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetUserByID(ctx context.Context, in *registrator.GetUserByIDRequest, opts ...grpc.CallOption) (*registrator.GetUserByIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetUserByIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetUserByIDRequest, ...grpc.CallOption) *registrator.GetUserByIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetUserByIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetUserByIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type RegistratorServiceClient_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetUserByIDRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetUserByID(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetUserByID_Call {
	return &RegistratorServiceClient_GetUserByID_Call{Call: _e.mock.On("GetUserByID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetUserByID_Call) Run(run func(ctx context.Context, in *registrator.GetUserByIDRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetUserByIDRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetUserByID_Call) Return(_a0 *registrator.GetUserByIDResponse, _a1 error) *RegistratorServiceClient_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetUserByTelegramID provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetUserByTelegramID(ctx context.Context, in *registrator.GetUserByTelegramIDRequest, opts ...grpc.CallOption) (*registrator.GetUserByTelegramIDResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetUserByTelegramIDResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetUserByTelegramIDRequest, ...grpc.CallOption) *registrator.GetUserByTelegramIDResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetUserByTelegramIDResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetUserByTelegramIDRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetUserByTelegramID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByTelegramID'
type RegistratorServiceClient_GetUserByTelegramID_Call struct {
	*mock.Call
}

// GetUserByTelegramID is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetUserByTelegramIDRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetUserByTelegramID(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetUserByTelegramID_Call {
	return &RegistratorServiceClient_GetUserByTelegramID_Call{Call: _e.mock.On("GetUserByTelegramID",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetUserByTelegramID_Call) Run(run func(ctx context.Context, in *registrator.GetUserByTelegramIDRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetUserByTelegramID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetUserByTelegramIDRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetUserByTelegramID_Call) Return(_a0 *registrator.GetUserByTelegramIDResponse, _a1 error) *RegistratorServiceClient_GetUserByTelegramID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetUserGames provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) GetUserGames(ctx context.Context, in *registrator.GetUserGamesRequest, opts ...grpc.CallOption) (*registrator.GetUserGamesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.GetUserGamesResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.GetUserGamesRequest, ...grpc.CallOption) *registrator.GetUserGamesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.GetUserGamesResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.GetUserGamesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_GetUserGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGames'
type RegistratorServiceClient_GetUserGames_Call struct {
	*mock.Call
}

// GetUserGames is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.GetUserGamesRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) GetUserGames(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_GetUserGames_Call {
	return &RegistratorServiceClient_GetUserGames_Call{Call: _e.mock.On("GetUserGames",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_GetUserGames_Call) Run(run func(ctx context.Context, in *registrator.GetUserGamesRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_GetUserGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.GetUserGamesRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_GetUserGames_Call) Return(_a0 *registrator.GetUserGamesResponse, _a1 error) *RegistratorServiceClient_GetUserGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// RegisterGame provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) RegisterGame(ctx context.Context, in *registrator.RegisterGameRequest, opts ...grpc.CallOption) (*registrator.RegisterGameResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.RegisterGameResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.RegisterGameRequest, ...grpc.CallOption) *registrator.RegisterGameResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.RegisterGameResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.RegisterGameRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_RegisterGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterGame'
type RegistratorServiceClient_RegisterGame_Call struct {
	*mock.Call
}

// RegisterGame is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.RegisterGameRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) RegisterGame(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_RegisterGame_Call {
	return &RegistratorServiceClient_RegisterGame_Call{Call: _e.mock.On("RegisterGame",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_RegisterGame_Call) Run(run func(ctx context.Context, in *registrator.RegisterGameRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_RegisterGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.RegisterGameRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_RegisterGame_Call) Return(_a0 *registrator.RegisterGameResponse, _a1 error) *RegistratorServiceClient_RegisterGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// RegisterPlayer provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) RegisterPlayer(ctx context.Context, in *registrator.RegisterPlayerRequest, opts ...grpc.CallOption) (*registrator.RegisterPlayerResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.RegisterPlayerResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.RegisterPlayerRequest, ...grpc.CallOption) *registrator.RegisterPlayerResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.RegisterPlayerResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.RegisterPlayerRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_RegisterPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterPlayer'
type RegistratorServiceClient_RegisterPlayer_Call struct {
	*mock.Call
}

// RegisterPlayer is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.RegisterPlayerRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) RegisterPlayer(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_RegisterPlayer_Call {
	return &RegistratorServiceClient_RegisterPlayer_Call{Call: _e.mock.On("RegisterPlayer",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_RegisterPlayer_Call) Run(run func(ctx context.Context, in *registrator.RegisterPlayerRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_RegisterPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.RegisterPlayerRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_RegisterPlayer_Call) Return(_a0 *registrator.RegisterPlayerResponse, _a1 error) *RegistratorServiceClient_RegisterPlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UnregisterGame provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) UnregisterGame(ctx context.Context, in *registrator.UnregisterGameRequest, opts ...grpc.CallOption) (*registrator.UnregisterGameResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.UnregisterGameResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.UnregisterGameRequest, ...grpc.CallOption) *registrator.UnregisterGameResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.UnregisterGameResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.UnregisterGameRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_UnregisterGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterGame'
type RegistratorServiceClient_UnregisterGame_Call struct {
	*mock.Call
}

// UnregisterGame is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.UnregisterGameRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) UnregisterGame(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_UnregisterGame_Call {
	return &RegistratorServiceClient_UnregisterGame_Call{Call: _e.mock.On("UnregisterGame",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_UnregisterGame_Call) Run(run func(ctx context.Context, in *registrator.UnregisterGameRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_UnregisterGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.UnregisterGameRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_UnregisterGame_Call) Return(_a0 *registrator.UnregisterGameResponse, _a1 error) *RegistratorServiceClient_UnregisterGame_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UnregisterPlayer provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) UnregisterPlayer(ctx context.Context, in *registrator.UnregisterPlayerRequest, opts ...grpc.CallOption) (*registrator.UnregisterPlayerResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.UnregisterPlayerResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.UnregisterPlayerRequest, ...grpc.CallOption) *registrator.UnregisterPlayerResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.UnregisterPlayerResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.UnregisterPlayerRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_UnregisterPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterPlayer'
type RegistratorServiceClient_UnregisterPlayer_Call struct {
	*mock.Call
}

// UnregisterPlayer is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.UnregisterPlayerRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) UnregisterPlayer(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_UnregisterPlayer_Call {
	return &RegistratorServiceClient_UnregisterPlayer_Call{Call: _e.mock.On("UnregisterPlayer",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_UnregisterPlayer_Call) Run(run func(ctx context.Context, in *registrator.UnregisterPlayerRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_UnregisterPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.UnregisterPlayerRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_UnregisterPlayer_Call) Return(_a0 *registrator.UnregisterPlayerResponse, _a1 error) *RegistratorServiceClient_UnregisterPlayer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdatePayment provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) UpdatePayment(ctx context.Context, in *registrator.UpdatePaymentRequest, opts ...grpc.CallOption) (*registrator.UpdatePaymentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.UpdatePaymentResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.UpdatePaymentRequest, ...grpc.CallOption) *registrator.UpdatePaymentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.UpdatePaymentResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.UpdatePaymentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_UpdatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePayment'
type RegistratorServiceClient_UpdatePayment_Call struct {
	*mock.Call
}

// UpdatePayment is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.UpdatePaymentRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) UpdatePayment(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_UpdatePayment_Call {
	return &RegistratorServiceClient_UpdatePayment_Call{Call: _e.mock.On("UpdatePayment",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_UpdatePayment_Call) Run(run func(ctx context.Context, in *registrator.UpdatePaymentRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_UpdatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.UpdatePaymentRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_UpdatePayment_Call) Return(_a0 *registrator.UpdatePaymentResponse, _a1 error) *RegistratorServiceClient_UpdatePayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdateUserEmail provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) UpdateUserEmail(ctx context.Context, in *registrator.UpdateUserEmailRequest, opts ...grpc.CallOption) (*registrator.UpdateUserEmailResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.UpdateUserEmailResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.UpdateUserEmailRequest, ...grpc.CallOption) *registrator.UpdateUserEmailResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.UpdateUserEmailResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.UpdateUserEmailRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_UpdateUserEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserEmail'
type RegistratorServiceClient_UpdateUserEmail_Call struct {
	*mock.Call
}

// UpdateUserEmail is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.UpdateUserEmailRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) UpdateUserEmail(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_UpdateUserEmail_Call {
	return &RegistratorServiceClient_UpdateUserEmail_Call{Call: _e.mock.On("UpdateUserEmail",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_UpdateUserEmail_Call) Run(run func(ctx context.Context, in *registrator.UpdateUserEmailRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_UpdateUserEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.UpdateUserEmailRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_UpdateUserEmail_Call) Return(_a0 *registrator.UpdateUserEmailResponse, _a1 error) *RegistratorServiceClient_UpdateUserEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdateUserName provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) UpdateUserName(ctx context.Context, in *registrator.UpdateUserNameRequest, opts ...grpc.CallOption) (*registrator.UpdateUserNameResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.UpdateUserNameResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.UpdateUserNameRequest, ...grpc.CallOption) *registrator.UpdateUserNameResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.UpdateUserNameResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.UpdateUserNameRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_UpdateUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserName'
type RegistratorServiceClient_UpdateUserName_Call struct {
	*mock.Call
}

// UpdateUserName is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.UpdateUserNameRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) UpdateUserName(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_UpdateUserName_Call {
	return &RegistratorServiceClient_UpdateUserName_Call{Call: _e.mock.On("UpdateUserName",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_UpdateUserName_Call) Run(run func(ctx context.Context, in *registrator.UpdateUserNameRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_UpdateUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.UpdateUserNameRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_UpdateUserName_Call) Return(_a0 *registrator.UpdateUserNameResponse, _a1 error) *RegistratorServiceClient_UpdateUserName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdateUserPhone provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) UpdateUserPhone(ctx context.Context, in *registrator.UpdateUserPhoneRequest, opts ...grpc.CallOption) (*registrator.UpdateUserPhoneResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.UpdateUserPhoneResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.UpdateUserPhoneRequest, ...grpc.CallOption) *registrator.UpdateUserPhoneResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.UpdateUserPhoneResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.UpdateUserPhoneRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_UpdateUserPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPhone'
type RegistratorServiceClient_UpdateUserPhone_Call struct {
	*mock.Call
}

// UpdateUserPhone is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.UpdateUserPhoneRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) UpdateUserPhone(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_UpdateUserPhone_Call {
	return &RegistratorServiceClient_UpdateUserPhone_Call{Call: _e.mock.On("UpdateUserPhone",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_UpdateUserPhone_Call) Run(run func(ctx context.Context, in *registrator.UpdateUserPhoneRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_UpdateUserPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.UpdateUserPhoneRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_UpdateUserPhone_Call) Return(_a0 *registrator.UpdateUserPhoneResponse, _a1 error) *RegistratorServiceClient_UpdateUserPhone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdateUserState provides a mock function with given fields: ctx, in, opts
func (_m *RegistratorServiceClient) UpdateUserState(ctx context.Context, in *registrator.UpdateUserStateRequest, opts ...grpc.CallOption) (*registrator.UpdateUserStateResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *registrator.UpdateUserStateResponse
	if rf, ok := ret.Get(0).(func(context.Context, *registrator.UpdateUserStateRequest, ...grpc.CallOption) *registrator.UpdateUserStateResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registrator.UpdateUserStateResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *registrator.UpdateUserStateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistratorServiceClient_UpdateUserState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserState'
type RegistratorServiceClient_UpdateUserState_Call struct {
	*mock.Call
}

// UpdateUserState is a helper method to define mock.On call
//  - ctx context.Context
//  - in *registrator.UpdateUserStateRequest
//  - opts ...grpc.CallOption
func (_e *RegistratorServiceClient_Expecter) UpdateUserState(ctx interface{}, in interface{}, opts ...interface{}) *RegistratorServiceClient_UpdateUserState_Call {
	return &RegistratorServiceClient_UpdateUserState_Call{Call: _e.mock.On("UpdateUserState",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *RegistratorServiceClient_UpdateUserState_Call) Run(run func(ctx context.Context, in *registrator.UpdateUserStateRequest, opts ...grpc.CallOption)) *RegistratorServiceClient_UpdateUserState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*registrator.UpdateUserStateRequest), variadicArgs...)
	})
	return _c
}

func (_c *RegistratorServiceClient_UpdateUserState_Call) Return(_a0 *registrator.UpdateUserStateResponse, _a1 error) *RegistratorServiceClient_UpdateUserState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewRegistratorServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewRegistratorServiceClient creates a new instance of RegistratorServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRegistratorServiceClient(t mockConstructorTestingTNewRegistratorServiceClient) *RegistratorServiceClient {
	mock := &RegistratorServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
